version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  NuGetOrgApiKey: 
    secure: 
  PUBLIC_NUGET_FEED_NAME: nuget.org
  PUBLIC_NUGET_FEED_SOURCE: https://www.nuget.org/
before_build:
- cmd: msbuild src/src.sln /t:restore /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
build:
  project: src/src.sln
  publish_nuget: true
  verbosity: minimal
after_build:
- cmd: msbuild src/src.sln /t:Pack /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: /src/**/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  skip_symbols: false
  artifact: /.*\.nupkg/